// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
export const CHROME_MODIFIER_CODES = [
	"AltLeft",
	"AltRight",
	"ControlLeft",
	"ControlRight",
	"MetaLeft",
	"MetaRight",
	"ShiftLeft",
	"ShiftRight",
] as const;

export const CHROME_CODES = [
	"ArrowDown",
	"ArrowLeft",
	"ArrowRight",
	"ArrowUp",
	"AudioVolumeDown",
	"AudioVolumeMute",
	"AudioVolumeUp",
	"Backquote",
	"Backslash",
	"Backspace",
	"BracketLeft",
	"BracketRight",
	"BrowserBack",
	"BrowserForward",
	"BrowserHome",
	"BrowserRefresh",
	"BrowserSearch",
	"BrowserStop",
	"CapsLock",
	"Comma",
	"ContextMenu",
	"Convert",
	"Copy",
	"Cut",
	"Delete",
	"Digit0",
	"Digit1",
	"Digit2",
	"Digit3",
	"Digit4",
	"Digit5",
	"Digit6",
	"Digit7",
	"Digit8",
	"Digit9",
	"Eject",
	"End",
	"Enter",
	"Equal",
	"Escape",
	"F1",
	"F2",
	"F3",
	"F4",
	"F5",
	"F6",
	"F7",
	"F8",
	"F9",
	"F10",
	"F11",
	"F12",
	"F13",
	"F14",
	"F15",
	"F16",
	"F17",
	"F18",
	"F19",
	"F20",
	"F21",
	"F22",
	"F23",
	"F24",
	"Help",
	"Home",
	"Insert",
	"IntlBackslash",
	"IntlRo",
	"IntlYen",
	"KanaMode",
	"KeyA",
	"KeyB",
	"KeyC",
	"KeyD",
	"KeyE",
	"KeyF",
	"KeyG",
	"KeyH",
	"KeyI",
	"KeyJ",
	"KeyK",
	"KeyL",
	"KeyM",
	"KeyN",
	"KeyO",
	"KeyP",
	"KeyQ",
	"KeyR",
	"KeyS",
	"KeyT",
	"KeyU",
	"KeyV",
	"KeyW",
	"KeyX",
	"KeyY",
	"KeyZ",
	"Lang1",
	"Lang2",
	"Lang3",
	"Lang4",
	"LaunchApp1",
	"LaunchApp2",
	"LaunchMail",
	"MediaPlayPause",
	"MediaSelect",
	"MediaStop",
	"MediaTrackNext",
	"MediaTrackPrevious",
	"Minus",
	"NonConvert",
	"Numpad0",
	"Numpad1",
	"Numpad2",
	"Numpad3",
	"Numpad4",
	"Numpad5",
	"Numpad6",
	"Numpad7",
	"Numpad8",
	"Numpad9",
	"NumpadAdd",
	"NumpadDecimal",
	"NumpadDivide",
	"NumpadEnter",
	"NumpadEqual",
	"NumpadMultiply",
	"NumpadSubtract",
	"PageDown",
	"PageUp",
	"Paste",
	"Pause",
	"Period",
	"Power",
	"PrintScreen",
	"Quote",
	"ScrollLock",
	"Semicolon",
	"Slash",
	"Space",
	"Tab",
	"Undo",
	"WakeUp",
] as const;

// export const CHROME_CODES_LOWER = [
// 	"arrowdown",
// 	"arrowleft",
// 	"arrowright",
// 	"arrowup",
// 	"audiovolumedown",
// 	"audiovolumemute",
// 	"audiovolumeup",
// 	"backquote",
// 	"backslash",
// 	"backspace",
// 	"bracketleft",
// 	"bracketright",
// 	"browserback",
// 	"browserforward",
// 	"browserhome",
// 	"browserrefresh",
// 	"browsersearch",
// 	"browserstop",
// 	"capslock",
// 	"comma",
// 	"contextmenu",
// 	"convert",
// 	"copy",
// 	"cut",
// 	"delete",
// 	"digit0",
// 	"digit1",
// 	"digit2",
// 	"digit3",
// 	"digit4",
// 	"digit5",
// 	"digit6",
// 	"digit7",
// 	"digit8",
// 	"digit9",
// 	"eject",
// 	"end",
// 	"enter",
// 	"equal",
// 	"escape",
// 	"f1",
// 	"f2",
// 	"f3",
// 	"f4",
// 	"f5",
// 	"f6",
// 	"f7",
// 	"f8",
// 	"f9",
// 	"f10",
// 	"f11",
// 	"f12",
// 	"f13",
// 	"f14",
// 	"f15",
// 	"f16",
// 	"f17",
// 	"f18",
// 	"f19",
// 	"f20",
// 	"f21",
// 	"f22",
// 	"f23",
// 	"f24",
// 	"help",
// 	"home",
// 	"insert",
// 	"intlbackslash",
// 	"intlro",
// 	"intlyen",
// 	"kanamode",
// 	"keya",
// 	"keyb",
// 	"keyc",
// 	"keyd",
// 	"keye",
// 	"keyf",
// 	"keyg",
// 	"keyh",
// 	"keyi",
// 	"keyj",
// 	"keyk",
// 	"keyl",
// 	"keym",
// 	"keyn",
// 	"keyo",
// 	"keyp",
// 	"keyq",
// 	"keyr",
// 	"keys",
// 	"keyt",
// 	"keyu",
// 	"keyv",
// 	"keyw",
// 	"keyx",
// 	"keyy",
// 	"keyz",
// 	"lang1",
// 	"lang2",
// 	"lang3",
// 	"lang4",
// 	"launchapp1",
// 	"launchapp2",
// 	"launchmail",
// 	"mediaplaypause",
// 	"mediaselect",
// 	"mediastop",
// 	"mediatracknext",
// 	"mediatrackprevious",
// 	"minus",
// 	"nonconvert",
// 	"numpad0",
// 	"numpad1",
// 	"numpad2",
// 	"numpad3",
// 	"numpad4",
// 	"numpad5",
// 	"numpad6",
// 	"numpad7",
// 	"numpad8",
// 	"numpad9",
// 	"numpadadd",
// 	"numpadddecimal",
// 	"numpadddivide",
// 	"numpadenter",
// 	"numpadequal",
// 	"numpadmultiply",
// 	"numpadsubtract",
// 	"pagedown",
// 	"pageup",
// 	"paste",
// 	"pause",
// 	"period",
// 	"power",
// 	"printscreen",
// 	"quote",
// 	"scrolllock",
// 	"semicolon",
// 	"shiftleft",
// 	"shiftright",
// 	"space",
// 	"tab",
// 	"undo",
// 	"wakeup",
// 	"",
// ] as const;

// export const CHROME_MODIFIER_CODES_LOWER = [
// 	"altleft",
// 	"altright",
// 	"controlleft",
// 	"controlright",
// 	"metaleft",
// 	"metaright",
// 	"shiftleft",
// 	"shiftright",
// ] as const;