import { UserConfig, defineConfig } from "vite";
import path from "path";
import builtins from "builtin-modules";
import react from "@vitejs/plugin-react";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(async ({ mode }) => {
	const { resolve } = path;
	const prod = mode === "production";
	return {
		build: {
      cssCodeSplit: false,
      emptyOutDir: false,
			// lib: {
			// 	entry: resolve(__dirname, "src/main.ts"),
			// 	fileName: () => "main.js",
			// 	formats: ["cjs"],
			// 	name: "main",
			// },
			minify: prod,
			outdir: "dist", // "./",
      rollupOptions: {
        external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtins,
				],
				input: {
					main: resolve(__dirname, "src/main.ts"),
					// styles: resolve(__dirname, "src/styles.css"),
				},
				output: {
					banner,
					entryFileNames: "[name].js",
					dir: "./",
					// assetFileNames: "styles.css",
				},
      },
      sourcemap: prod ? false : "inline",
			target: "es2022",
		},
		plugins: [react()],
		resolve: {
			alias: {
				"@": path.resolve(__dirname, "./src"),
			},
		},
	} as UserConfig;
});
