import { UserConfig, defineConfig, Plugin, PluginHookUtils } from "vite";
import path from "path";
import builtins from "builtin-modules";
import react from "@vitejs/plugin-react";

// const banner = `/*
// THIS IS A GENERATED/BUNDLED FILE BY VITE
// if you want to view the source, please visit the github repository of this plugin
// */
// `;

const logWatcherConfig: Plugin = {
	name: "log-watcher-config",
	configResolved(config) {
		console.log("\nVite build configuration props:");
		Object.keys(config).forEach((k) => console.log(`\t${k}`));
		console.log("\nVite config.build keys:");
		Object.keys(config.build).forEach((k) => console.log(`\t${k}`));
		console.log("\nVite  keys:");
		Object.keys(config.build).forEach((k) => console.log(`\t${k}`));
		if (config.build.watch) {
			console.log("\nVite config.build.watch keys:");
			Object.keys(config.build.watch).forEach((k) =>
				console.log(`\t${k}`)
			);
		} else {
			console.log("\nVite config.build.watch is undefined");
		}
	},
	watchChange(id, change) {
		console.log("Watch change detected:", { id, change });
	},
};

export default defineConfig(async ({ mode }) => {
	const { resolve } = path;
	const prod = mode === "production";
	console.log(`vite.config.ts / defineConfig / mode=${mode} / prod=${prod}`);

	return {
		build: {
			cssCodeSplit: false,
			emptyOutDir: false,
			lib: {
				entry: resolve(__dirname, "src/main.ts"),
				fileName: () => "main.js",
				formats: ["cjs"],
				name: "main",
			},
			minify: prod,
			outDir: "dist",
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtins,
				],
				input: {
					main: resolve(__dirname, "src/main.ts"),
				},
				output: {
					entryFileNames: "main.js",
					dir: "./",
					// assetFileNames: "styles.css",
        },
        watch: {},
			},
			sourcemap: prod ? false : "inline",
			target: "es2022",
      watch: {
        chokidar: {
          usePolling: true,
          interval: 1000,
          ignored: ["main.js", "main.js.map"],
        },
      },
		},
		plugins: [react(), logWatcherConfig],
		resolve: {
			alias: {
				"@": path.resolve(__dirname, "./src"),
			},
		},
	} as UserConfig;
});
